// <auto-generated />
using System;
using AngularandASPNETCORE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppliDbContext))]
    [Migration("20220909182945_initial6")]
    partial class initial6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Employee", b =>
                {
                    b.Property<int>("idemployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idemployee"), 1L, 1);

                    b.Property<string>("arabicfullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateJoin")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gender")
                        .HasColumnType("int");

                    b.Property<int>("idjob")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("password")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("passwordsalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("salary")
                        .HasColumnType("int");

                    b.HasKey("idemployee");

                    b.HasIndex("idjob");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("BackEnd.Models.Job", b =>
                {
                    b.Property<int>("idjob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idjob"), 1L, 1);

                    b.Property<string>("jobdescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idjob");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("BackEnd.Models.Employee", b =>
                {
                    b.HasOne("BackEnd.Models.Job", "job")
                        .WithMany("employess")
                        .HasForeignKey("idjob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job");
                });

            modelBuilder.Entity("BackEnd.Models.Job", b =>
                {
                    b.Navigation("employess");
                });
#pragma warning restore 612, 618
        }
    }
}
